### ISSUE TITLE
Parse different appsettings.json files based on environment

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#135]
consider having:
appsettings.pipelines.json
appsettings.macos.json
appsettings.linux.json
appsettings.windows.json 
[AB#7050](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7050)

**Comment by georgend** [comment]
@zengin I would like to tackle this one as well as handling Read Settings and Write Settings.
Where write settings are for creating data. We can add client permission portioning to the work as well.

**Comment by zengin** [comment]
Resolved by #427 and #443
