### ISSUE TITLE
Granting consent is blocked by a cryptic error message in Azure portal

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#158]
After exceeding a certain number of permissions on an app, granting consent gets blocked by the following error:
```
AADSTS650051: Value length '14144' is out of the valid range of '1' to '8000' for property 'DelegationScope'.
```
Consenting through login.microsoftonline.com URL works in some cases but not in others.

Expected:
We should be able to grant all permissions. 
[AB#7794](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7794)

**Comment by finsharp** [comment]
Issue was raised on [uservoice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/40100899-failed-to-admin-consent-for-microsoft-graph-api-fr?edit=1) as well. 
Team was able to repro the issue [Q&A](https://docs.microsoft.com/en-us/answers/questions/246111/granting-consent-for-all-permissions-fails-with-cr.html)

**Comment by zengin** [comment]
We have worked around this issue by giving read-only permissions because we are running only GET tests at the moment. Keeping the issue open to track the resolution of root cause before next phase, which requires write permissions.

**Comment by zengin** [comment]
Related: https://github.com/microsoftgraph/microsoft-graph-docs/issues/11431

**Comment by zengin** [comment]
We have a workaround for this problem. We create one delegated app per permission and request token from a specific app for a particular scope.
