### ISSUE TITLE
Document how to setup a tenant for execution

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#190]
- CDX tenant creation
- An app registration in Azure Portal
- Application manifest update to get all "read-only" permissions (https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/dev/scripts/applyReadPermissionsToManifest.ps1)
- Create a client secret
- Make the application a public client 
[AB#8244](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8244)

**Comment by fey101** [comment]
Ready for review https://microsoft.sharepoint-df.com/teams/GraphTooling/_layouts/15/Doc.aspx?sourcedoc={17bb0920-66d0-4428-9e86-2509fcd4de4f}&action=edit&wd=target%28Raptor.one%7Cab528e48-146b-452e-998f-2bfa818a8c67%2FUntitled%20Page%7C9879f685-3d28-4d91-a2d9-e8013a12699f%2F%29

**Comment by zengin** [comment]
Looks good to me. Thanks!
