### ISSUE TITLE
[Java] test performance improvements

### ISSUE THREAD

**Issue by baywet** [microsoftgraph/msgraph-sdk-raptor#201]
Right now the java raptor tests take upwards of an hour for beta. This trips the ADO time limit and makes the tests flaky on top of making it painful to use.
This is because we currently create a shell project, copy the snippet, and fire the compilation for every single test. The gradle process start and reporting takes a lot of time, and is repeated for each snippet.

If we instead had a gradle multi-project structure, with one shell (deps and common configuration) and one subproject per snippet, we'd be able to fire the compilation once. Saving a lot of cold start and stop time per unit test.

That pre-compilation sequence would be fired in the test initialization method (once for the data set) and the unit test would only match the result (stored in a file?) and report it up to Nunit. 
[AB#8389](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8389)

**Comment by zengin** [comment]
cleaning up open issues: no longer an issue after #825
