### ISSUE TITLE
Extend data generation scripts to delegated permissions

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#251]
- For now, /me and /users/<user-id> APIs can be categorized to use delegated access.
- We need a step to fetch permission list from devx api, fetch a token, and use that in `Connect-MgGraph`. It needs to happen once per test, because scopes change from one test to another. 
[AB#9218](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9218)

**Comment by fey101** [comment]
Closed when the combined effort work was merged in PR https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/272
