### ISSUE TITLE
Investigate usefulness of pnp provisioning templates in raptor

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/msgraph-sdk-raptor#297]
Became a need after a review of PR https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/279 which suggested use of pnp templates to allow declarations of dependencies and an easier way of provisioning tenants. 
[AB#10023](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10023)

**Comment by fey101** [comment]
Investigation covered:

- Does pnp provisioning templates or the engine help with the current need of filling missing data?
  No. The pnp templates will help in provisioning a tenant but for starters you need an ideal tenant from which to export an ideal tenant template. So we will still need to fill missing data which at the moment we are doing using powershell scripts.

- Is it an easier way of provisioning tenants?
 Yes. If the aim is to provision a site-supporting tenant, then it's an easier way of provisioning tenants. I have also reached out to one of the docs contributors to verify if I might have missed out on other ways to provision tenants. For now, it doesn't feel like it would serve our current purpose but could come in handy if we ever get in situations where we need to provision lots of tenants quick.

- Are the language declarations useful and/or easier?
 Yes, they are easily understandable since they are in xml format and the provisioning template can also be exported from an `ideal` tenant and as such easily useable to provision subsequent tenants/sites.

- Is the language syntax easily understandable and applicable?
   Yes. the language is based on xml syntax and there also a couple of sample provisioning templates available on the repo for study and to help in kickstarting and scaffolding a provisioning template

Summary:
Use of pnp templates is a great way to help in quickly provisioning  a sharepoint site or office365 tenant. However in order to make the process much easier and practical you need to have an "ideal" site/tenant which models what you would like to export to other tenants. Otherwise creating provisioning templates by hand can be cumbersome for a large project. We therefore will continue to use the powershell scripts to fill missing data for our first 2 tenants currently in use and once we are done with filling missing data we may consider using the pnp templates to transfer this data to other tenants on a need basis.

**Comment by baywet** [comment]
@fey101 thanks for the recap. There's one main point where I disagree with the conclusion:
You don't necessarily need an ideal tenant, you can create the template yourself with the data you want. The advantage of using PnP provisioning when available instead of our custom approach is that we get something off the shelf instead of re-inventing the wheel.

**Comment by fey101** [comment]
@baywet , I agree, but that would need lots of effort given we are looking at templates to support the entire MSGraph space including outlook calendars, excel worksheets, files and everything else supported by the graph rest endpoint (hopefully even permissions), which I doubt are supported by the pnp tenant templates for now. I have also reached out to @VesaJuvonen , one of the doc writers just to verify whether this templates are supported. Also not to forget, that our main interest is a couple **data** endpoints which are known beforehand and not necessarily the organization of content across the pages. For example if I were to provision a site using the templates, the end goal would be just to retrieve the following details only
```json

  "site": {
    "_value": "<site-id>",
    "list": {
      "_value": "<site-list-id>",
      "listItem": {
        "_value": "<site-list-listitem-id>",
        "listItemVersion": {
          "_value": "<site-list-listItem-listItemVersion-id>"
        }
      }
    }
```
To create a provisioning template to only reflect this useful data without overdoing the design will be challenging without an existing ideal site to use as reference.

Once we have a reference tenant, we can now adapt the off-the shelf approach for other tenants.

Also we are currently not re-inventing the wheel coz we are filling the missing data on top of what is already provided by default in contoso demo tenant.

**Comment by baywet** [comment]
Sure, you know the requirements better. I was only suggesting a tool that could make things easier in the ODSP/Teams/AAD space. Thanks for going through a thorough evaluation process. Closing.

**Comment by fey101** [comment]
Thanks for the review and the initial suggestion baywet. Also adding the response from Vesa Juvonen here for future reference.

![image](https://user-images.githubusercontent.com/11347476/123609679-8ead6b80-d808-11eb-9465-dbafbd631c8c.png)

Mentioned link attached https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2021-03.md#tenant
