### ISSUE TITLE
DriveItem, Subscription, EducationClass and EducationSchool. WorkForceIntegration

### ISSUE THREAD

**Issue by fey101** [microsoftgraph/msgraph-sdk-raptor#299]
Fill missing data for above resources 
[AB#10063](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10063)

**Comment by zengin** [comment]
This was closed before introducing educationSchool, I opened a new issue to address that: #609. @fey101, please share if you have any findings around if there are any blockers around creating an educationSchool object.
