### ISSUE TITLE
Refactor authentication code to implement TokenCredentials

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-raptor#307]
Version 4 of the .Net sdk will implement the use of `TokenCredentials` from `Azure.Identity`. 

It would be great if the raptor tests and code implemented TokenCredentials rather IAuthenticationProvider instances from the now deprecated Microsoft.Graph.Auth packages.

[AB#10158](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10158)

**Comment by georgend** [comment]
Will the snippets be changed as well?

**Comment by andrueastman** [comment]
The raptor instances will ideally cease to use `IAuthenticationProvider` instances from Microsoft.Graph.Auth and can now use the `TokenCredentialAuthProvider` which takes in Azure.Identity TokenCredentials.

**Comment by georgend** [comment]
Doesn't that also require a change to the snippet to use token credential? Otherwise the full intent of the snippet will not be captured. It's wiser to execute the snippet, as much as possible, as it is. To keep its original Structure and intent.
