### ISSUE TITLE
Missing Data: Call, CallRecords

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#320]
[AB#10247](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10247)

**Comment by zengin** [comment]
{callRecords.callRecord-id} test cases:

- [ ] callrecord-getpstncalls-csharp-V1-executes
- [ ] get-callrecord-expanded-csharp-V1-executes
- [ ] get-callrecord-csharp-V1-executes
- [ ] get-callrecord-sessions-expanded-csharp-V1-executes
- [ ] get-callrecord-sessions-csharp-V1-executes
- [ ] callrecord-getdirectroutingcalls-csharp-V1-executes

**Comment by fey101** [comment]
Needs creation of new bot and adding capabilities as documented here https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/registering-calling-bot

**Comment by fey101** [comment]
It also requires the account to be authenticated via authenticator app.
Also when logging in with our test tenant I am warned with following error:
"[Teams Toolkit] Your Microsoft 365 account doesn't have a sideloading permission. Without this permission, you cannot load your app within Teams. Contact to your administrator to resolve this issue or signin another account with sideloading permission."
