### ISSUE TITLE
Missing Data: Contract

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#322]
Important: Exists in partner tenants only. Partner tenants are Azure AD tenants that belong to Microsoft partners who are either part of Microsoft Cloud Solution Provider, Office 365 Syndication, or Microsoft Advisor partner programs.

[AB#10249](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10249)

**Comment by georgend** [comment]
Will be resolved by linked PR, where it shall be marked as a known issue until resolved.

**Comment by zengin** [comment]
reactivating this to link from the known issue. This issue has important details about the missing data.
