### ISSUE TITLE
Missing Data: Printer

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#325]
Related Items:
- PrinterConnector
- PrinterShare
- PrintOperation
- PrintService has missing ChildItem -> PrintServiceEndpoint
- PrintTaskDefinition and Children
- PrintUsageByPrinter
- PrintUsageByUser
[AB#10252](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10252)

**Comment by zengin** [comment]
This is closed before adding some of the data were added. Opened #627
