### ISSUE TITLE
Add Typescript/JS validation

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-sdk-raptor#381]
Extends our languages by adding validation for typescript/JS 
[AB#10702](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10702)

**Comment by nikithauc** [comment]
Linking this to Epic  - https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/498

**Comment by zengin** [comment]
A few questions that come to mind:
1. Do we share code with Kiota SDK Generation and TypeScript Snippet Generation? In other words, do we have an independent snippet generation logic or do we have logic that uses code from SDK Generation? In either case, this logic should be made available to be consumed by DevX API for the on-the-fly generation scenario in GE.
2. Should the snippet generation logic consume OData CSDL or OpenAPI description? If it is going to use Kiota, it has to be the latter.
3. Release plan: This testing needs to be done in a branch of docs repo. We can't publish the snippets into the docs without publishing the Kiota-generated SDKs, but we can probably run the snippet generation process on-the-fly as part of Raptor validation. And it should be OK to push these into a docs branch given that Kiota is already public.
4. What does it mean to compile a TS snippet? Is there a compiler? What is the artifact that compiler generates? Can that artifact be used for executing snippets against a demo tenant?

**Comment by rkodev** [comment]
Typescript E2E builds has been set up. Currently we have 2 pipelines. 
1. Code generator that refreshes the SDK
2. Raptor tests Typescript. (Known Failures and Weekly tests)

**Comment by rkodev** [comment]
Issue was closed by https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/821
