### ISSUE TITLE
Scale appsettings.json fields

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#413]
Because we have a lot of pipelines, adding a field into `appsettings.json` file requires adding a corresponding variable into each pipeline and updating the `transformAppSettings.ps1` file to read that variable to to feed `appsettings.json`.

A few possible alternatives:
1. variable groups from Azure DevOps
2. Having only `RaptorStroageConnectionString` in the variables and downloading `appsettings.json` from blob storage.

@georgend @fey101 any ideas?

**Comment by georgend** [comment]
@zengin 
I prefer the second option Howerver, for more resiliency and to handle secrets as well, I would suggest using Azure App Configuration (with Azure Key Vault behind it for secrets). This would allow us to use Azure App Configuration Labels to manage environments (Staging, Production etc).

https://docs.microsoft.com/en-us/azure/azure-app-configuration/howto-labels-aspnet-core?tabs=core5x
