### ISSUE TITLE
Data Policy Operation Exception

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#488]
To avoid the following exception and aid in reproducibility when executing Personal Data Export, consider deleting `RequestInfo.json` from Blob Storage before executing the following request. 
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/704c1338b0c228bdd4f13dc5fc4d821d3f392509/scripts/TenantSetup/TenantHttpData/dataPolicyOperation/dataPolicyOperation.ps1#L15-L20
```
{
   "error":{
      "code":"StorageLocationAlreadyUsed",
      "message":"Storage destination has already been used for an export. If this is not true, delete 'RequestInfo.json' from the container and try again.",
      "innerError":{
         "date":"2021-10-07T14:49:41",
         "request-id":"eb2fb33e-2e56-4b4d-80e8-57917f30e356",
         "client-request-id":"eb2fb33e-2e56-4b4d-80e8-57917f30e356"
      }
   }
}
```

**Comment by zengin** [comment]
reopening this because `dataPolicyOperation` value is empty string in current identifier.json file in the blob storage.
