### ISSUE TITLE
MissingData: No rubric in assignment

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#507]
Test case: get-rubric-csharp-V1-executes

Error code: 20241

Error message: Entity not found. Rubric id:   d9d3c62f-fd17-4a8e-bd8b-44f5df90de73

**Comment by fey101** [comment]
closed by PR #656

**Comment by zengin** [comment]
I think we need to attach rubric to an assignment in order to make this test pass. Creating the rubric alone is not enough. Steps to follow:

https://docs.microsoft.com/en-us/graph/api/educationassignment-put-rubric?view=graph-rest-1.0&tabs=http
