### ISSUE TITLE
orgContact doesn't have a manager

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#511]
Test Case: get-manager-1-csharp-V1-executes

@georgend we have the following note in the read scripts. I wonder if the orgContact already exists in the tenant and the following query was failing for some reason, or the data was created by a one-off run of a creation script. I couldn't find a creation script checked in. Please share if you have any context around it.
```
# no data
# $contact = Request-DelegatedResource -Uri "me/contacts?`$top=1"
```

**Comment by georgend** [comment]
Read Default Data does handle orgContact
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/1009b82f00e39c217174db34059fc7963923c48a/scripts/TenantSetup/DefaultData/readDefaultData.ps1#L106-L110

**Comment by georgend** [comment]
@zengin I am beginning to think that the query to get an orgContact manager is not possible:-
- There is no endpoint to create an orgContact, however one can be created via admin panel/admin center, I was able to add a new contact and get their details from the API.
![image](https://user-images.githubusercontent.com/1641829/140182760-7d797076-68c5-4fc9-a1a7-a67b2a3d34e3.png)

- The API to assign a manager, only allows setting a user's manager to be an orgContact. It doesn't support setting an orgContacts manager.  https://docs.microsoft.com/en-us/graph/api/user-post-manager?view=graph-rest-1.0&tabs=http

**Comment by zengin** [comment]
@georgend isn't an orgContact a regular user, who can also have a manager? Can we add a user with manager as an orgContact of our default user?

**Comment by zengin** [comment]
> Read Default Data does handle orgContact
> 
> https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/1009b82f00e39c217174db34059fc7963923c48a/scripts/TenantSetup/DefaultData/readDefaultData.ps1#L106-L110

@georgend, do you have any insights into why we noted that the endpoint returned "no data"? I just want to make sure that the orgContact is not added without a reproducible script.
