### ISSUE TITLE
directoryObject should be assigned to a deleted item

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#513]
Test Case: `get-directory-csharp-V1-executes`

We are currently assigning the same value to `user-id` and `directoryObject-id` but our admin user is not deleted, so the query fails with `Request_ResourceNotFound`

**Comment by georgend** [comment]
Two options:-
Add this as an edge case and override `{directoryObject-id}` with an added `deletedDirectoryObject` identifier in identifiers.json
Change the snippet to read something different such as `{deletedDirectoryObject-id}`
