### ISSUE TITLE
Missing Data: Education Assignment Resource

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#572]
The Snippets Below Require Education Assignment Resource `educationAssignmentResource-id`
- [ ] get-educationlinkresource-from-educationassignment-csharp-Beta-executes
- [ ] get-educationfileresource-from-educationassignment-csharp-Beta-executes 
- [ ] get-educationpowerpointresource-from-educationassignment-csharp-Beta-executes
- [ ] get-educationfileresource-from-educationassignment-csharp-Beta-executes
- [ ] get-educationexcelresource-from-educationassignment-csharp-Beta-executes

**Comment by zengin** [comment]
This is no longer beta only. Removing the beta tag.

**Comment by zengin** [comment]
- [ ] get-educationlinkresource-from-educationassignment-csharp-V1-executes
- [ ] get-educationpowerpointresource-from-educationassignment-csharp-V1-executes
- [ ] get-educationmediaresource-from-educationassignment-csharp-V1-executes
- [ ] get-educationexcelresource-from-educationassignment-csharp-V1-executes
- [ ] get-educationfileresource-from-educationassignment-csharp-V1-executes
