### ISSUE TITLE
Create a T4 template with basic structure required for graph sample to run.

### ISSUE THREAD

**Issue by titusgicheru** [microsoftgraph/msgraph-sdk-raptor#6]
Considerations here are;
- Ability to include MetadataReference given a path. We will be compiling different versions of **Microsoft.Graph** and **Microsoft.Graph.Core**.
- Inject a snippet code in the appropriate section within the T4 run-time template.

**Comment by zengin** [comment]
String replace covers all code compilation scenarios that we have as of today.
