### ISSUE TITLE
Missing Data: {appConsentRequest-id}

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#612]
Test Cases:
- [ ] list-userconsentrequest-csharp-V1-executes
- [ ] get-userconsentrequest-csharp-V1-executes
- [ ] get-appconsentrequest-csharp-V1-executes
- [ ] userconsentrequest-filterbycurrentuser-csharp-V1-executes

**Comment by georgend** [comment]
https://docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0

These APIs lack Create endpoints and can only be created through UI interaction.
