### ISSUE TITLE
Missing Data: {oAuth2PermissionGrant-id}

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#622]
Test Case:
- [x] get-oauth2permissiongrant-csharp-V1-executes

**Comment by georgend** [comment]
Already covered by https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/59d98cf4df6d357138d3c69e40ef0bb70a564583/scripts/TenantSetup/DefaultData/readDefaultData.ps1#L146-L150
Data already in identifiers json and test passes.
