### ISSUE TITLE
Cannot create HostedContents in a Chat item in Chat.ps1

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#749]
Cannot create message with hosted content in the new tenant. 
Expected the request below, in the new tenant to return HostedContents, however it failed after running chat.ps1.

Possible issue at 
https://github.com/microsoftgraph/msgraph-sdk-raptor/blob/dd9d058028847b85a72d4de053f6fde089e23c93/scripts/TenantSetup/TenantHttpData/Team/chat.ps1#L44-L57

https://graph.microsoft.com/v1.0/chats/19:4db6af9a5618458480d118993336cbe9@thread.v2/messages/1641511122959/hostedContents

**Comment by fey101** [comment]
Fixed by PR #https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/758
