### ISSUE TITLE
Propagation delay between /me/findrooms and /places/microsoft.graph.room 

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#754]
When a room is created in the Admin portal, it can be immediately returned by /me/findrooms, however /places/microsoft.graph.room requires 48hrs for data to propagate/sync and be returned. 

Should there be a caveat to APIs users on this behavior?

@pixieofhugs I would like your help getting clarity regarding the sync delay and whether it needs to be a documented item. 

https://github.com/microsoftgraph/microsoft-graph-docs/issues/15460

**Comment by zengin** [comment]
this is not high priority given that the data creation is not programmatic.
