### ISSUE TITLE
Investigate Running PowerShell Tests on Linux Agents

### ISSUE THREAD

**Issue by georgend** [microsoftgraph/msgraph-sdk-raptor#800]
Currently PowerShell tests are executing in a Windows Agent, due to an issue with how runspaces are initialized on linux. 
Investigating the issue.

**Comment by georgend** [comment]
https://stackoverflow.com/questions/64455064/how-do-i-use-the-powershell-sdk-package-in-a-net-core-app-on-ubuntu-linux

**Comment by ddyett** [comment]
George can you clarify when we plan to look at this?

**Comment by georgend** [comment]
It was a "nice to have" at the time the issue was created. The priority then was just to make the tests run. 

To see whether this is doable, an quick experiment to run the tests on Linux would be the easiest way to know if its doable or completely blocked.

**Comment by zengin** [comment]
I have addressed this in an earlier PR. The PowerShell tests are now running more reliably on linux agents: https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/1077
