### ISSUE TITLE
PowerShell number of tests fluctuates

### ISSUE THREAD

**Issue by zengin** [microsoftgraph/msgraph-sdk-raptor#937]
![image](https://user-images.githubusercontent.com/803311/161586288-3d7b9c9b-1257-40cb-876d-e497c88af273.png)

**Expected behavior**
Same number of tests found.

**Comment by timayabi2020** [comment]
@zengin 
This PR (https://github.com/microsoftgraph/msgraph-sdk-raptor/pull/988) seemed to have fixed this issue. I will proceed to close it.
![image](https://user-images.githubusercontent.com/10947120/164219432-34641a1d-c402-4890-9427-90efeab07185.png)

**Comment by zengin** [comment]
@timayabi2020 I don't quite understand how that solves the issue we have identified: "two parallel jobs running and failure on one of them cancels the the other." The PR that was checked in only changes which tests are going to be picked up. Please note that this is not happening for every run, so I'd like to make sure that the result is not a false-positive.

**Comment by timayabi2020** [comment]
> @timayabi2020 I don't quite understand how that solves the issue we have identified: "two parallel jobs running and failure on one of them cancels the the other." The PR that was checked in only changes which tests are going to be picked up. Please note that this is not happening for every run, so I'd like to make sure that the result is not a false-positive.

@zengin noted. I've put the status under "needs investigation"

**Comment by timayabi2020** [comment]
@zengin. After monitoring the dashboard for some time, powershell tests are stable. Migration of the agent pool to 1ES and having a pipeline for each test (Eliminating parallel jobs) has solved the fluctuation issue. We are now able to focus on pushing the passrates up. Therefore I suggest that we have this issue closed




![Image](https://user-images.githubusercontent.com/10947120/174016458-8ce8c07a-79d2-4371-b759-e43f7ade41e7.png)

**Comment by zengin** [comment]
@timayabi2020 thanks for the update.
